[package]
name = "jack_mix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = { version ="0.9.0", features = ["dlopen"] }
crossbeam-channel = "0.5.2"
egui = "0.17.0"